// Plantear un Algoritmo del Area de Un triangulo

Proceso // ESTAMOS INICIANDO EL PROCESO
	
Algoritmo AreaDeUnTriangulo // ESTAMOS DEFINIENDO EL NOMBRE DEL ALGORITMO
	
Definir base, altura, area Como REAL // AQUI ESATMOS DEFINIENDO 
 
Escribir "---Estamos Calculando el Área de un Triangulo---" // AQUI LE ESTAMOS BRINDANDO AL CLIENTE LA BIENVENIDA A NUESTRO CALCULADOR DE AREA Y ALTURA DE UN TRIANGULO
Escribir "" //AQUI ESTAMOS HACIENDO UN SALTO DE LINEA PARA DAR MEJOR RESULTADO
Escribir "Ingrese la Base de su Triangulo: " // AQUI LE ESTAMOS PIDIENDO ALN USUARIO QUE INGRESE SU DATO
Leer base // ESTAMOS LLAMANDO LA VARIABLE DE LA BASE
Escribir "Ingrese la Altura de su Triangulo: " // AQUI LE ESTAMOS PIDIENDO ALN USUARIO QUE INGRESE SU DATO
Leer altura // ESTAMOS LLAMANDO LA VARIABLE DE LA ALTURA
area<-base*altura/2 // AQUI ESTAMOS APLICANDO LOS PROCEDIMIENTOS PARA OBTENER EL RESULTADO EN EL CUAL APLICAMOS EL LLAMADO LAS VARIABLES DE DE AREA, APLICAMOS LA ASIGNACIÓN, Y NUEVAMENTE LLAMAMOS LAS VARIABLES DE BASE POR ALTURA Y LA DIVISIÓN ENTRE 2 
Escribir "" //AQUI ESTAMOS HACIENDO UN SALTO DE LINEA PARA DAR MEJOR RESULTADO
Escribir "----------------------------------------------------------------------------------------------------------" // AQUI ESTAMOS HACIENDO UN SALTO DE LINEA PARA DAR MEJOR RESULTADO
ESCRIBIR "EL ÁREA DEL TRIANGULO EN EL QUE CALCULAMOS ( ", BASE," ) COMO DE BASE Y ( ", ALTURA, " ) COMO DE ALTURA ES DE: ", AREA // ESTAMOS RROJANDO LA SALIDA DEL CALCULO REALIZADO EN EL CUAL LE MOSTRAMOS AL USUARIO LOS DATOS QUE SEÑALO COMO LA BASE Y LA ALTURA  ASI ARROJANDO EL RESULTADO
Escribir "----------------------------------------------------------------------------------------------------------" //AQUI ESTAMOS HACIENDO UN SALTO DE LINEA PARA DAR MEJOR RESULTADO
FinProceso // ESTAMOS CULMINANDO EL PROCESO
